export const data = {
  results: {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 14,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 205,
    healthScore: 35,
    creditsText: "afrolems.com",
    sourceName: "afrolems.com",
    pricePerServing: 67.93,
    extendedIngredients: [
      {
        id: 20081,
        aisle: "Baking",
        image: "flour.png",
        consistency: "SOLID",
        name: "flour",
        nameClean: "wheat flour",
        original: "1.5 cups of flour",
        originalName: "flour",
        amount: 1.5,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 1.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 187.5,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 19296,
        aisle: "Nut butters, Jams, and Honey",
        image: "honey.png",
        consistency: "LIQUID",
        name: "honey",
        nameClean: "honey",
        original: "30 ml honey",
        originalName: "honey",
        amount: 30.0,
        unit: "ml",
        meta: [],
        measures: {
          us: {
            amount: 1.454,
            unitShort: "fl. oz",
            unitLong: "fl. ozs",
          },
          metric: {
            amount: 30.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1090,
        aisle: "Baking",
        image: "milk-powdered.jpg",
        consistency: "SOLID",
        name: "powdered milk",
        nameClean: "powdered milk",
        original: "1 tablespoon of powdered milk",
        originalName: "powdered milk",
        amount: 1.0,
        unit: "tablespoon",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "1/2 teaspoon salt",
        originalName: "salt",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "warm water",
        nameClean: "water",
        original: "150 ml warm water",
        originalName: "warm water",
        amount: 150.0,
        unit: "ml",
        meta: [],
        measures: {
          us: {
            amount: 5.073,
            unitShort: "fl. oz",
            unitLong: "fl. ozs",
          },
          metric: {
            amount: 150.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 18375,
        aisle: "Baking",
        image: "yeast-granules.jpg",
        consistency: "SOLID",
        name: "yeast",
        nameClean: "dry yeast",
        original: "1 teaspoon yeast",
        originalName: "yeast",
        amount: 1.0,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
    ],
    id: 716276,
    title: "Doughnuts",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: "https://www.afrolems.com/2014/03/25/doughnuts-recipe/",
    image: "https://img.spoonacular.com/recipes/716276-556x370.jpg",
    imageType: "jpg",
    nutrition: {
      nutrients: [
        {
          name: "Calories",
          amount: 430.24,
          unit: "kcal",
          percentOfDailyNeeds: 21.51,
        },
        {
          name: "Fat",
          amount: 2.04,
          unit: "g",
          percentOfDailyNeeds: 3.14,
        },
        {
          name: "Saturated Fat",
          amount: 0.79,
          unit: "g",
          percentOfDailyNeeds: 4.92,
        },
        {
          name: "Carbohydrates",
          amount: 91.33,
          unit: "g",
          percentOfDailyNeeds: 30.44,
        },
        {
          name: "Net Carbohydrates",
          amount: 88.34,
          unit: "g",
          percentOfDailyNeeds: 32.12,
        },
        {
          name: "Sugar",
          amount: 19.34,
          unit: "g",
          percentOfDailyNeeds: 21.49,
        },
        {
          name: "Cholesterol",
          amount: 3.64,
          unit: "mg",
          percentOfDailyNeeds: 1.21,
        },
        {
          name: "Sodium",
          amount: 602.56,
          unit: "mg",
          percentOfDailyNeeds: 26.2,
        },
        {
          name: "Alcohol",
          amount: 0.0,
          unit: "g",
          percentOfDailyNeeds: 100.0,
        },
        {
          name: "Alcohol %",
          amount: 0.0,
          unit: "%",
          percentOfDailyNeeds: 100.0,
        },
        {
          name: "Protein",
          amount: 11.36,
          unit: "g",
          percentOfDailyNeeds: 22.73,
        },
        {
          name: "Vitamin B1",
          amount: 0.92,
          unit: "mg",
          percentOfDailyNeeds: 61.18,
        },
        {
          name: "Folate",
          amount: 209.78,
          unit: "µg",
          percentOfDailyNeeds: 52.44,
        },
        {
          name: "Selenium",
          amount: 32.69,
          unit: "µg",
          percentOfDailyNeeds: 46.7,
        },
        {
          name: "Vitamin B2",
          amount: 0.58,
          unit: "mg",
          percentOfDailyNeeds: 34.03,
        },
        {
          name: "Manganese",
          amount: 0.66,
          unit: "mg",
          percentOfDailyNeeds: 33.22,
        },
        {
          name: "Vitamin B3",
          amount: 6.21,
          unit: "mg",
          percentOfDailyNeeds: 31.05,
        },
        {
          name: "Iron",
          amount: 4.5,
          unit: "mg",
          percentOfDailyNeeds: 24.98,
        },
        {
          name: "Phosphorus",
          amount: 141.12,
          unit: "mg",
          percentOfDailyNeeds: 14.11,
        },
        {
          name: "Fiber",
          amount: 2.99,
          unit: "g",
          percentOfDailyNeeds: 11.97,
        },
        {
          name: "Copper",
          amount: 0.17,
          unit: "mg",
          percentOfDailyNeeds: 8.25,
        },
        {
          name: "Vitamin B5",
          amount: 0.72,
          unit: "mg",
          percentOfDailyNeeds: 7.2,
        },
        {
          name: "Magnesium",
          amount: 25.85,
          unit: "mg",
          percentOfDailyNeeds: 6.46,
        },
        {
          name: "Zinc",
          amount: 0.96,
          unit: "mg",
          percentOfDailyNeeds: 6.41,
        },
        {
          name: "Calcium",
          amount: 52.63,
          unit: "mg",
          percentOfDailyNeeds: 5.26,
        },
        {
          name: "Potassium",
          amount: 176.34,
          unit: "mg",
          percentOfDailyNeeds: 5.04,
        },
        {
          name: "Vitamin B6",
          amount: 0.08,
          unit: "mg",
          percentOfDailyNeeds: 4.05,
        },
        {
          name: "Vitamin D",
          amount: 0.39,
          unit: "µg",
          percentOfDailyNeeds: 2.63,
        },
        {
          name: "Vitamin B12",
          amount: 0.12,
          unit: "µg",
          percentOfDailyNeeds: 2.05,
        },
      ],
      properties: [
        {
          name: "Glycemic Index",
          amount: 86.14,
          unit: "",
        },
        {
          name: "Glycemic Load",
          amount: 61.64,
          unit: "",
        },
        {
          name: "Inflammation Score",
          amount: -7.0,
          unit: "",
        },
        {
          name: "Nutrition Score",
          amount: 15.614347759796226,
          unit: "%",
        },
      ],
      flavonoids: [
        {
          name: "Cyanidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Petunidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Delphinidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Malvidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Pelargonidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Peonidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Catechin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epigallocatechin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epicatechin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epicatechin 3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epigallocatechin 3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Thearubigins",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Eriodictyol",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Hesperetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Naringenin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Apigenin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Luteolin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Isorhamnetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Kaempferol",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Myricetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Quercetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3,3'-digallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3'-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Gallocatechin",
          amount: 0.0,
          unit: "",
        },
      ],
      ingredients: [
        {
          id: 20081,
          name: "flour",
          amount: 0.75,
          unit: "cups",
          nutrients: [
            {
              name: "Choline",
              amount: 9.75,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.74,
              unit: "mg",
              percentOfDailyNeeds: 61.18,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.39,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.92,
              unit: "g",
              percentOfDailyNeeds: 3.14,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.21,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.05,
            },
            {
              name: "Calcium",
              amount: 14.06,
              unit: "mg",
              percentOfDailyNeeds: 5.26,
            },
            {
              name: "Selenium",
              amount: 31.78,
              unit: "µg",
              percentOfDailyNeeds: 46.7,
            },
            {
              name: "Phosphorus",
              amount: 101.25,
              unit: "mg",
              percentOfDailyNeeds: 14.11,
            },
            {
              name: "Vitamin B3",
              amount: 5.53,
              unit: "mg",
              percentOfDailyNeeds: 31.05,
            },
            {
              name: "Net Carbohydrates",
              amount: 69.01,
              unit: "g",
              percentOfDailyNeeds: 32.12,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.63,
            },
            {
              name: "Folic Acid",
              amount: 144.38,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 171.56,
              unit: "µg",
              percentOfDailyNeeds: 52.44,
            },
            {
              name: "Vitamin K",
              amount: 0.28,
              unit: "µg",
              percentOfDailyNeeds: 0.35,
            },
            {
              name: "Copper",
              amount: 0.14,
              unit: "mg",
              percentOfDailyNeeds: 8.25,
            },
            {
              name: "Iron",
              amount: 4.35,
              unit: "mg",
              percentOfDailyNeeds: 24.98,
            },
            {
              name: "Magnesium",
              amount: 20.63,
              unit: "mg",
              percentOfDailyNeeds: 6.46,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.41,
              unit: "mg",
              percentOfDailyNeeds: 7.2,
            },
            {
              name: "Manganese",
              amount: 0.64,
              unit: "mg",
              percentOfDailyNeeds: 33.22,
            },
            {
              name: "Protein",
              amount: 9.68,
              unit: "g",
              percentOfDailyNeeds: 22.73,
            },
            {
              name: "Fiber",
              amount: 2.53,
              unit: "g",
              percentOfDailyNeeds: 11.97,
            },
            {
              name: "Vitamin B2",
              amount: 0.46,
              unit: "mg",
              percentOfDailyNeeds: 34.03,
            },
            {
              name: "Sodium",
              amount: 1.88,
              unit: "mg",
              percentOfDailyNeeds: 26.2,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.08,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.06,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Carbohydrates",
              amount: 71.54,
              unit: "g",
              percentOfDailyNeeds: 30.44,
            },
            {
              name: "Vitamin B6",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 4.05,
            },
            {
              name: "Sugar",
              amount: 0.25,
              unit: "g",
              percentOfDailyNeeds: 21.49,
            },
            {
              name: "Zinc",
              amount: 0.66,
              unit: "mg",
              percentOfDailyNeeds: 6.41,
            },
            {
              name: "Saturated Fat",
              amount: 0.15,
              unit: "g",
              percentOfDailyNeeds: 4.92,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 0.7,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.53,
            },
            {
              name: "Potassium",
              amount: 100.31,
              unit: "mg",
              percentOfDailyNeeds: 5.04,
            },
            {
              name: "Calories",
              amount: 341.25,
              unit: "kcal",
              percentOfDailyNeeds: 21.51,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 19296,
          name: "honey",
          amount: 15.0,
          unit: "ml",
          nutrients: [
            {
              name: "Choline",
              amount: 0.47,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 61.18,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.14,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.21,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.05,
            },
            {
              name: "Calcium",
              amount: 1.29,
              unit: "mg",
              percentOfDailyNeeds: 5.26,
            },
            {
              name: "Selenium",
              amount: 0.17,
              unit: "µg",
              percentOfDailyNeeds: 46.7,
            },
            {
              name: "Phosphorus",
              amount: 0.86,
              unit: "mg",
              percentOfDailyNeeds: 14.11,
            },
            {
              name: "Vitamin B3",
              amount: 0.03,
              unit: "mg",
              percentOfDailyNeeds: 31.05,
            },
            {
              name: "Net Carbohydrates",
              amount: 17.67,
              unit: "g",
              percentOfDailyNeeds: 32.12,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.63,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.43,
              unit: "µg",
              percentOfDailyNeeds: 52.44,
            },
            {
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.35,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 8.25,
            },
            {
              name: "Iron",
              amount: 0.09,
              unit: "mg",
              percentOfDailyNeeds: 24.98,
            },
            {
              name: "Magnesium",
              amount: 0.43,
              unit: "mg",
              percentOfDailyNeeds: 6.46,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 7.2,
            },
            {
              name: "Manganese",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 33.22,
            },
            {
              name: "Fluoride",
              amount: 1.5,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Protein",
              amount: 0.06,
              unit: "g",
              percentOfDailyNeeds: 22.73,
            },
            {
              name: "Fiber",
              amount: 0.04,
              unit: "g",
              percentOfDailyNeeds: 11.97,
            },
            {
              name: "Vitamin B2",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 34.03,
            },
            {
              name: "Sodium",
              amount: 0.86,
              unit: "mg",
              percentOfDailyNeeds: 26.2,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Carbohydrates",
              amount: 17.71,
              unit: "g",
              percentOfDailyNeeds: 30.44,
            },
            {
              name: "Vitamin B6",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 4.05,
            },
            {
              name: "Sugar",
              amount: 17.65,
              unit: "g",
              percentOfDailyNeeds: 21.49,
            },
            {
              name: "Zinc",
              amount: 0.05,
              unit: "mg",
              percentOfDailyNeeds: 6.41,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 4.92,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 0.7,
            },
            {
              name: "Vitamin C",
              amount: 0.11,
              unit: "mg",
              percentOfDailyNeeds: 0.53,
            },
            {
              name: "Potassium",
              amount: 11.18,
              unit: "mg",
              percentOfDailyNeeds: 5.04,
            },
            {
              name: "Calories",
              amount: 65.34,
              unit: "kcal",
              percentOfDailyNeeds: 21.51,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 1090,
          name: "powdered milk",
          amount: 0.5,
          unit: "tablespoon",
          nutrients: [
            {
              name: "Choline",
              amount: 4.46,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 61.18,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.02,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 1.0,
              unit: "g",
              percentOfDailyNeeds: 3.14,
            },
            {
              name: "Cholesterol",
              amount: 3.64,
              unit: "mg",
              percentOfDailyNeeds: 1.21,
            },
            {
              name: "Vitamin B12",
              amount: 0.12,
              unit: "µg",
              percentOfDailyNeeds: 2.05,
            },
            {
              name: "Calcium",
              amount: 34.2,
              unit: "mg",
              percentOfDailyNeeds: 5.26,
            },
            {
              name: "Selenium",
              amount: 0.61,
              unit: "µg",
              percentOfDailyNeeds: 46.7,
            },
            {
              name: "Phosphorus",
              amount: 29.1,
              unit: "mg",
              percentOfDailyNeeds: 14.11,
            },
            {
              name: "Vitamin B3",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 31.05,
            },
            {
              name: "Net Carbohydrates",
              amount: 1.44,
              unit: "g",
              percentOfDailyNeeds: 32.12,
            },
            {
              name: "Vitamin D",
              amount: 0.39,
              unit: "µg",
              percentOfDailyNeeds: 2.63,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 1.39,
              unit: "µg",
              percentOfDailyNeeds: 52.44,
            },
            {
              name: "Vitamin K",
              amount: 0.08,
              unit: "µg",
              percentOfDailyNeeds: 0.35,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 8.25,
            },
            {
              name: "Iron",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 24.98,
            },
            {
              name: "Magnesium",
              amount: 3.19,
              unit: "mg",
              percentOfDailyNeeds: 6.46,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.09,
              unit: "mg",
              percentOfDailyNeeds: 7.2,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 33.22,
            },
            {
              name: "Protein",
              amount: 0.99,
              unit: "g",
              percentOfDailyNeeds: 22.73,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 11.97,
            },
            {
              name: "Vitamin B2",
              amount: 0.05,
              unit: "mg",
              percentOfDailyNeeds: 34.03,
            },
            {
              name: "Sodium",
              amount: 13.91,
              unit: "mg",
              percentOfDailyNeeds: 26.2,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.3,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Carbohydrates",
              amount: 1.44,
              unit: "g",
              percentOfDailyNeeds: 30.44,
            },
            {
              name: "Vitamin B6",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 4.05,
            },
            {
              name: "Sugar",
              amount: 1.44,
              unit: "g",
              percentOfDailyNeeds: 21.49,
            },
            {
              name: "Zinc",
              amount: 0.13,
              unit: "mg",
              percentOfDailyNeeds: 6.41,
            },
            {
              name: "Saturated Fat",
              amount: 0.63,
              unit: "g",
              percentOfDailyNeeds: 4.92,
            },
            {
              name: "Vitamin A",
              amount: 35.03,
              unit: "IU",
              percentOfDailyNeeds: 0.7,
            },
            {
              name: "Vitamin C",
              amount: 0.32,
              unit: "mg",
              percentOfDailyNeeds: 0.53,
            },
            {
              name: "Potassium",
              amount: 49.88,
              unit: "mg",
              percentOfDailyNeeds: 5.04,
            },
            {
              name: "Calories",
              amount: 18.6,
              unit: "kcal",
              percentOfDailyNeeds: 21.51,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 2047,
          name: "salt",
          amount: 0.25,
          unit: "teaspoon",
          nutrients: [
            {
              name: "Choline",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 61.18,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.14,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.21,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.05,
            },
            {
              name: "Calcium",
              amount: 0.36,
              unit: "mg",
              percentOfDailyNeeds: 5.26,
            },
            {
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 46.7,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 14.11,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 31.05,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 32.12,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.63,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 52.44,
            },
            {
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.35,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 8.25,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 24.98,
            },
            {
              name: "Magnesium",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 6.46,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 7.2,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 33.22,
            },
            {
              name: "Fluoride",
              amount: 0.03,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 22.73,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 11.97,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 34.03,
            },
            {
              name: "Sodium",
              amount: 581.37,
              unit: "mg",
              percentOfDailyNeeds: 26.2,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 30.44,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 4.05,
            },
            {
              name: "Sugar",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 21.49,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.41,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 4.92,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 0.7,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.53,
            },
            {
              name: "Potassium",
              amount: 0.12,
              unit: "mg",
              percentOfDailyNeeds: 5.04,
            },
            {
              name: "Calories",
              amount: 0.0,
              unit: "kcal",
              percentOfDailyNeeds: 21.51,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 14412,
          name: "warm water",
          amount: 75.0,
          unit: "ml",
          nutrients: [
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 11.97,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.14,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 22.73,
            },
            {
              name: "Sodium",
              amount: 3.75,
              unit: "mg",
              percentOfDailyNeeds: 26.2,
            },
            {
              name: "Calcium",
              amount: 2.25,
              unit: "mg",
              percentOfDailyNeeds: 5.26,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 14.11,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 32.12,
            },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 30.44,
            },
            {
              name: "Zinc",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 6.41,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 8.25,
            },
            {
              name: "Magnesium",
              amount: 0.75,
              unit: "mg",
              percentOfDailyNeeds: 6.46,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 24.98,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 33.22,
            },
            {
              name: "Fluoride",
              amount: 19.35,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 5.04,
            },
            {
              name: "Calories",
              amount: 0.0,
              unit: "kcal",
              percentOfDailyNeeds: 21.51,
            },
          ],
        },
        {
          id: 18375,
          name: "yeast",
          amount: 0.5,
          unit: "teaspoon",
          nutrients: [
            {
              name: "Choline",
              amount: 0.5,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.17,
              unit: "mg",
              percentOfDailyNeeds: 61.18,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.12,
              unit: "g",
              percentOfDailyNeeds: 3.14,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.21,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.05,
            },
            {
              name: "Calcium",
              amount: 0.47,
              unit: "mg",
              percentOfDailyNeeds: 5.26,
            },
            {
              name: "Selenium",
              amount: 0.12,
              unit: "µg",
              percentOfDailyNeeds: 46.7,
            },
            {
              name: "Phosphorus",
              amount: 9.91,
              unit: "mg",
              percentOfDailyNeeds: 14.11,
            },
            {
              name: "Vitamin B3",
              amount: 0.63,
              unit: "mg",
              percentOfDailyNeeds: 31.05,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.22,
              unit: "g",
              percentOfDailyNeeds: 32.12,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.63,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 36.4,
              unit: "µg",
              percentOfDailyNeeds: 52.44,
            },
            {
              name: "Vitamin K",
              amount: 0.01,
              unit: "µg",
              percentOfDailyNeeds: 0.35,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 8.25,
            },
            {
              name: "Iron",
              amount: 0.03,
              unit: "mg",
              percentOfDailyNeeds: 24.98,
            },
            {
              name: "Magnesium",
              amount: 0.84,
              unit: "mg",
              percentOfDailyNeeds: 6.46,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.21,
              unit: "mg",
              percentOfDailyNeeds: 7.2,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 33.22,
            },
            {
              name: "Protein",
              amount: 0.63,
              unit: "g",
              percentOfDailyNeeds: 22.73,
            },
            {
              name: "Fiber",
              amount: 0.42,
              unit: "g",
              percentOfDailyNeeds: 11.97,
            },
            {
              name: "Vitamin B2",
              amount: 0.06,
              unit: "mg",
              percentOfDailyNeeds: 34.03,
            },
            {
              name: "Sodium",
              amount: 0.79,
              unit: "mg",
              percentOfDailyNeeds: 26.2,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.07,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Carbohydrates",
              amount: 0.64,
              unit: "g",
              percentOfDailyNeeds: 30.44,
            },
            {
              name: "Vitamin B6",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 4.05,
            },
            {
              name: "Sugar",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 21.49,
            },
            {
              name: "Zinc",
              amount: 0.12,
              unit: "mg",
              percentOfDailyNeeds: 6.41,
            },
            {
              name: "Saturated Fat",
              amount: 0.02,
              unit: "g",
              percentOfDailyNeeds: 4.92,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 0.7,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.53,
            },
            {
              name: "Potassium",
              amount: 14.86,
              unit: "mg",
              percentOfDailyNeeds: 5.04,
            },
            {
              name: "Calories",
              amount: 5.06,
              unit: "kcal",
              percentOfDailyNeeds: 21.51,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
      ],
      caloricBreakdown: {
        percentProtein: 10.59,
        percentFat: 4.28,
        percentCarbs: 85.13,
      },
      weightPerServing: {
        amount: 197,
        unit: "g",
      },
    },
    summary:
      'If you have around <b>45 minutes</b> to spend in the kitchen, Doughnuts might be an amazing <b>lacto ovo vegetarian</b> recipe to try. For <b>68 cents per serving</b>, you get a breakfast that serves 2. One serving contains <b>445 calories</b>, <b>13g of protein</b>, and <b>2g of fat</b>. If you have warm water, honey, powdered milk, and a few other ingredients on hand, you can make it. It is brought to you by Afrolems. Several people made this recipe, and 205 would say it hit the spot. With a spoonacular <b>score of 96%</b>, this dish is tremendous. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/how-to-make-doughnuts-with-video-and-coffee-biscoff-bacon-doughnuts-573590">How to make doughnuts (with video) and Coffee-Biscoff-Bacon Doughnuts</a>, <a href="https://spoonacular.com/recipes/everything-doughnuts-742597">Everything Doughnuts</a>, and <a href="https://spoonacular.com/recipes/cranberry-doughnuts-428199">Cranberry Doughnuts</a>.',
    cuisines: [],
    dishTypes: ["morning meal", "brunch", "breakfast"],
    diets: ["lacto ovo vegetarian"],
    occasions: [],
    instructions:
      "In a bowl mix the water with the yeast and honey, whisk and allow to sit for 15 minutes or until the mixture is foamy.Mix the flour with the salt and powdered milk and pour the yeast mixture into the bowl.Knead the dough till its elastic and not sticky and cover and leave to double in size. This could take 1-2 hours.On a lightly floured surface, roll out your dough but not to thin so your doughnuts are not flat and cut the dough into circles. If You have a doughnut cutter use that, if not use a small round shaped cover or bowl to make your circles and a smaller container for the middle hole. You can improvise and use the mouth of a plastic bottle to make the hole in the middle.Leave to rise for another 45 minutes.Heat up your oil and fry the doughnuts till they are brown on both sides.Vanilla GlazeMix 1 cup of powdered sugar with 30 ml of milk and 1 teaspoon of vanilla. Whisk till its properly mixed and drizzle the doughnuts with it. Add sprinkles for garnishingChocolate GlazeI used a chocolate sauce and drizzled over the doughnuts with sprinkles to top it.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "In a bowl mix the water with the yeast and honey, whisk and allow to sit for 15 minutes or until the mixture is foamy.",
            ingredients: [
              {
                id: 19296,
                name: "honey",
                localizedName: "honey",
                image: "honey.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 18375,
                name: "yeast",
                localizedName: "yeast",
                image: "yeast-granules.jpg",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
              },
            ],
            length: {
              number: 15,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Mix the flour with the salt and powdered milk and pour the yeast mixture into the bowl.Knead the dough till its elastic and not sticky and cover and leave to double in size. This could take 1-2 hours.On a lightly floured surface, roll out your dough but not to thin so your doughnuts are not flat and cut the dough into circles. If You have a doughnut cutter use that, if not use a small round shaped cover or bowl to make your circles and a smaller container for the middle hole. You can improvise and use the mouth of a plastic bottle to make the hole in the middle.Leave to rise for another 45 minutes.",
            ingredients: [
              {
                id: 1090,
                name: "powdered milk",
                localizedName: "powdered milk",
                image: "milk-powdered.jpg",
              },
              {
                id: 0,
                name: "dough",
                localizedName: "dough",
                image: "pizza-dough",
              },
              {
                id: 20081,
                name: "all purpose flour",
                localizedName: "all purpose flour",
                image: "flour.png",
              },
              {
                id: 18375,
                name: "yeast",
                localizedName: "yeast",
                image: "yeast-granules.jpg",
              },
              {
                id: 12135,
                name: "nuts",
                localizedName: "nuts",
                image: "nuts-mixed.jpg",
              },
              {
                id: 0,
                name: "roll",
                localizedName: "roll",
                image: "dinner-yeast-rolls.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "https://spoonacular.com/cdn/equipment_100x100/bowl.jpg",
              },
            ],
            length: {
              number: 165,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Heat up your oil and fry the doughnuts till they are brown on both sides.Vanilla Glaze",
            ingredients: [
              {
                id: 1052050,
                name: "vanilla",
                localizedName: "vanilla",
                image: "vanilla.jpg",
              },
              {
                id: 0,
                name: "glaze",
                localizedName: "glaze",
                image: "",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Mix 1 cup of powdered sugar with 30 ml of milk and 1 teaspoon of vanilla.",
            ingredients: [
              {
                id: 19336,
                name: "powdered sugar",
                localizedName: "powdered sugar",
                image: "powdered-sugar.jpg",
              },
              {
                id: 1052050,
                name: "vanilla",
                localizedName: "vanilla",
                image: "vanilla.jpg",
              },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Whisk till its properly mixed and drizzle the doughnuts with it.",
            ingredients: [],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 6,
            step: "Add sprinkles for garnishing",
            ingredients: [
              {
                id: 93645,
                name: "sprinkles",
                localizedName: "sprinkles",
                image: "colorful-sprinkles.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 7,
            step: "Chocolate GlazeI used a chocolate sauce and drizzled over the doughnuts with sprinkles to top it.",
            ingredients: [
              {
                id: 10019348,
                name: "hot fudge sauce",
                localizedName: "hot fudge sauce",
                image: "chocolate-glaze.png",
              },
              {
                id: 19081,
                name: "chocolate",
                localizedName: "chocolate",
                image:
                  "https://spoonacular.com/cdn/ingredients_100x100/milk-chocolate.jpg",
              },
              {
                id: 93645,
                name: "sprinkles",
                localizedName: "sprinkles",
                image: "colorful-sprinkles.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 95.76062774658203,
    spoonacularSourceUrl: "https://spoonacular.com/doughnuts-716276",
  },
};
